#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import sys
import time
import urllib.error
import urllib.request
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping


ARTIFACT_NAME = "alert-webhook-drill-record"
MANUAL_PLACEHOLDER = "待填写"

RECORD_TEMPLATE = """# Alert Webhook Drill Record

| Field | Value |
| --- | --- |
| 时间 | |
| 负责人 | |
| 接收端 | |
| GitHub Actions run URL | |
| `send` mode | |
| `status` input | |
| HTTP firing response | |
| HTTP resolved response | |
| 触发告警 | |
| 收到时间 | |
| 恢复告警 | |
| Artifact `alert-webhook-drill-record` | |
| 结论 | |
"""


@dataclass(frozen=True)
class DeliveryResult:
    status: str
    dry_run: bool
    http_status: int = 0
    response_body: str = ""


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")


def _mask_url(url: str) -> str:
    if "://" not in url:
        return "<redacted>"
    scheme, rest = url.split("://", 1)
    host = rest.split("/", 1)[0]
    return f"{scheme}://{host}/<redacted>"


def build_payload(status: str, alert_name: str, receiver: str) -> dict[str, Any]:
    now = _utc_now()
    ends_at = "0001-01-01T00:00:00Z" if status == "firing" else now
    return {
        "version": "4",
        "groupKey": f'{{}}:{{alertname="{alert_name}"}}',
        "truncatedAlerts": 0,
        "status": status,
        "receiver": receiver,
        "groupLabels": {"alertname": alert_name},
        "commonLabels": {
            "alertname": alert_name,
            "service": "ops-drill",
            "severity": "warning",
        },
        "commonAnnotations": {
            "summary": "Alert webhook drill",
            "description": "Synthetic payload generated by scripts/ops/alert_webhook_drill.py",
        },
        "externalURL": "http://alertmanager:9093",
        "alerts": [
            {
                "status": status,
                "labels": {
                    "alertname": alert_name,
                    "service": "ops-drill",
                    "severity": "warning",
                    "instance": "manual-drill",
                },
                "annotations": {
                    "summary": "Alert webhook drill",
                    "description": "Synthetic Alertmanager webhook payload for receiver verification.",
                },
                "startsAt": now,
                "endsAt": ends_at,
                "generatorURL": "manual://alert-webhook-drill",
                "fingerprint": "opsdrill00000001",
            }
        ],
    }


def post_json(url: str, payload: dict[str, Any], timeout: float) -> tuple[int, str]:
    data = json.dumps(payload).encode("utf-8")
    request = urllib.request.Request(
        url,
        data=data,
        headers={"Content-Type": "application/json", "User-Agent": "stock-platform-alert-drill/1.0"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            body = response.read(500).decode("utf-8", errors="replace")
            return response.status, body
    except urllib.error.HTTPError as exc:
        body = exc.read(500).decode("utf-8", errors="replace")
        return exc.code, body
    except urllib.error.URLError as exc:
        return 0, f"ERROR: {exc.reason}"


def _markdown_cell(value: str) -> str:
    return (
        value.replace("\r\n", "\n")
        .replace("\r", "\n")
        .replace("\n", "<br>")
        .replace("|", "\\|")
        .strip()
    )


def _markdown_row(label: str, value: str) -> str:
    return f"| {label} | {_markdown_cell(value)} |"


def _github_run_url(explicit_url: str | None, env: Mapping[str, str]) -> str:
    if explicit_url:
        return explicit_url

    configured_url = env.get("DRILL_GITHUB_RUN_URL")
    if configured_url:
        return configured_url

    repository = env.get("GITHUB_REPOSITORY")
    run_id = env.get("GITHUB_RUN_ID")
    if repository and run_id:
        server_url = env.get("GITHUB_SERVER_URL", "https://github.com").rstrip("/")
        return f"{server_url}/{repository}/actions/runs/{run_id}"

    return MANUAL_PLACEHOLDER


def _owner(explicit_owner: str | None, env: Mapping[str, str]) -> str:
    return explicit_owner or env.get("DRILL_OWNER") or env.get("GITHUB_ACTOR") or MANUAL_PLACEHOLDER


def _http_response_summary(status: str, status_input: str, results: list[DeliveryResult]) -> str:
    result = next((item for item in results if item.status == status), None)
    if result is None:
        if status_input == "both":
            return "not sent (previous payload failed)"
        return f"not sent (status input: {status_input})"
    if result.dry_run:
        return "not sent (dry-run)"
    if result.http_status > 0:
        return f"HTTP {result.http_status}"
    return result.response_body or "ERROR: request failed"


def _trigger_summary(alert_name: str, status_input: str, results: list[DeliveryResult]) -> str:
    parts: list[str] = []
    for status in ("firing", "resolved"):
        result = next((item for item in results if item.status == status), None)
        if result is None:
            if status_input == "both":
                parts.append(f"{status} payload not sent because a previous payload failed")
            else:
                parts.append(f"{status} payload not sent because status input was {status_input}")
            continue
        if result.dry_run:
            parts.append(f"{status} payload generated only (dry-run)")
        elif result.http_status > 0:
            parts.append(f"{status} payload sent (HTTP {result.http_status})")
        else:
            parts.append(f"{status} payload failed ({result.response_body or 'request failed'})")
    return f"{alert_name}: " + "; ".join(parts)


def render_record_markdown(
    args: argparse.Namespace,
    results: list[DeliveryResult],
    generated_at: str | None = None,
    env: Mapping[str, str] | None = None,
) -> str:
    env = env or os.environ
    generated_at = generated_at or _utc_now()
    dry_run = args.dry_run or not args.send
    rows = (
        ("时间", generated_at),
        ("负责人", _owner(args.owner, env)),
        ("接收端", args.receiver),
        ("GitHub Actions run URL", _github_run_url(args.github_run_url, env)),
        ("`send` mode", "false (dry-run)" if dry_run else "true"),
        ("`status` input", args.status),
        ("HTTP firing response", _http_response_summary("firing", args.status, results)),
        ("HTTP resolved response", _http_response_summary("resolved", args.status, results)),
        ("触发告警", _trigger_summary(args.alert_name, args.status, results)),
        ("收到时间", MANUAL_PLACEHOLDER),
        ("恢复告警", MANUAL_PLACEHOLDER),
        (
            "Artifact `alert-webhook-drill-record`",
            f"{ARTIFACT_NAME} artifact generated by this workflow run; upload step follows this script.",
        ),
        ("结论", MANUAL_PLACEHOLDER),
    )
    return "\n".join(
        [
            "# Alert Webhook Drill Record",
            "",
            "| Field | Value |",
            "| --- | --- |",
            *(_markdown_row(label, value) for label, value in rows),
            "",
        ]
    )


def write_record(path: str | None, markdown: str, label: str) -> None:
    if not path or path == "-":
        print(markdown, end="")
        return
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(markdown, encoding="utf-8")
    print(f"Wrote {label} to {output}")


def write_record_template(path: str | None) -> None:
    write_record(path, RECORD_TEMPLATE, "drill record template")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Dry-run or send an Alertmanager webhook drill payload.")
    parser.add_argument("--url", default=os.getenv("ALERT_WEBHOOK_URL"), help="Webhook URL. Defaults to ALERT_WEBHOOK_URL.")
    parser.add_argument("--send", action="store_true", help="Actually POST to the webhook URL. Omit for dry-run.")
    parser.add_argument("--dry-run", action="store_true", help="Print the payload without sending. This is the default.")
    parser.add_argument("--status", choices=("firing", "resolved", "both"), default="firing", help="Payload status to generate.")
    parser.add_argument("--alert-name", default="OpsWebhookDrill", help="Synthetic alert name.")
    parser.add_argument(
        "--receiver",
        default=os.getenv("ALERT_WEBHOOK_RECEIVER", "ops-webhook"),
        help="Alertmanager receiver name.",
    )
    parser.add_argument("--timeout", type=float, default=10.0, help="HTTP timeout in seconds.")
    parser.add_argument("--record-template", action="store_true", help="Generate the drill record template instead of a payload.")
    parser.add_argument("--record-output", help="Write a prefilled drill record to this file. Use '-' for stdout.")
    parser.add_argument("--owner", help="Drill owner. Defaults to DRILL_OWNER, then GITHUB_ACTOR.")
    parser.add_argument(
        "--github-run-url",
        help="GitHub Actions run URL. Defaults to DRILL_GITHUB_RUN_URL or GitHub Actions environment variables.",
    )
    parser.add_argument("--sleep-between", type=float, default=1.0, help="Delay between firing and resolved when --status both.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])

    if args.record_template:
        write_record_template(args.record_output)
        return 0

    if not args.url:
        print("ERROR: provide --url or set ALERT_WEBHOOK_URL", file=sys.stderr)
        return 2

    statuses = ("firing", "resolved") if args.status == "both" else (args.status,)
    dry_run = args.dry_run or not args.send
    generated_at = _utc_now()
    results: list[DeliveryResult] = []
    exit_code = 0

    for index, status in enumerate(statuses):
        payload = build_payload(status, args.alert_name, args.receiver)
        if dry_run:
            print(f"DRY-RUN: would POST {status} payload to {_mask_url(args.url)}")
            print(json.dumps(payload, ensure_ascii=False, indent=2))
            results.append(DeliveryResult(status=status, dry_run=True))
        else:
            code, body = post_json(args.url, payload, args.timeout)
            results.append(DeliveryResult(status=status, dry_run=False, http_status=code, response_body=body))
            if code > 0:
                print(f"POST {status} payload to {_mask_url(args.url)} -> HTTP {code}")
            else:
                print(f"POST {status} payload to {_mask_url(args.url)} -> ERROR")
            if body:
                print(body)
            if code < 200 or code >= 300:
                exit_code = 1
                break
        if index < len(statuses) - 1 and args.sleep_between > 0:
            time.sleep(args.sleep_between)

    if args.record_output:
        markdown = render_record_markdown(args, results, generated_at=generated_at)
        write_record(args.record_output, markdown, "prefilled drill record")

    return exit_code


if __name__ == "__main__":
    raise SystemExit(main())
