#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path


@dataclass(frozen=True)
class Field:
    name: str
    label: str
    env_var: str


FIELDS = (
    Field("drill_date_utc", "Drill date (UTC)", "DRILL_DATE_UTC"),
    Field("owner", "Owner", "DRILL_OWNER"),
    Field("repository", "Repository", "DRILL_REPOSITORY"),
    Field("commit_sha", "Commit SHA", "DRILL_COMMIT_SHA"),
    Field("app_version", "APP_VERSION", "DRILL_APP_VERSION"),
    Field("environment", "Environment", "DRILL_ENVIRONMENT"),
    Field("ci_run_url", "CI workflow run URL", "DRILL_CI_RUN_URL"),
    Field("db_integration_result", "`db-integration` job result", "DRILL_DB_INTEGRATION_RESULT"),
    Field("alert_drill_run_url", "Alert Webhook Drill run URL", "DRILL_ALERT_DRILL_RUN_URL"),
    Field("deployment_smoke", "Deployment smoke", "DRILL_DEPLOYMENT_SMOKE"),
    Field("rollback_check", "Rollback check", "DRILL_ROLLBACK_CHECK"),
    Field("blocking_issues", "Blocking issues", "DRILL_BLOCKING_ISSUES"),
    Field("follow_up_owner", "Follow-up owner", "DRILL_FOLLOW_UP_OWNER"),
    Field("follow_up_due_date", "Follow-up due date", "DRILL_FOLLOW_UP_DUE_DATE"),
)


GITHUB_ENV_FALLBACKS = {
    "owner": "GITHUB_ACTOR",
    "repository": "GITHUB_REPOSITORY",
    "commit_sha": "GITHUB_SHA",
    "app_version": "GITHUB_SHA",
}


def _utc_now_iso_z() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _github_ci_run_url() -> str:
    server_url = os.getenv("GITHUB_SERVER_URL", "").rstrip("/")
    repository = os.getenv("GITHUB_REPOSITORY", "")
    run_id = os.getenv("GITHUB_RUN_ID", "")
    if server_url and repository and run_id:
        return f"{server_url}/{repository}/actions/runs/{run_id}"
    return ""


def _field_default(field: Field) -> str:
    drill_value = os.getenv(field.env_var)
    if drill_value is not None:
        return drill_value
    if field.name == "drill_date_utc":
        return _utc_now_iso_z()
    if field.name == "ci_run_url":
        return _github_ci_run_url()
    github_env_var = GITHUB_ENV_FALLBACKS.get(field.name)
    if github_env_var:
        return os.getenv(github_env_var, "")
    return ""


def _table_value(value: str | None) -> str:
    if value is None:
        return ""
    return value.replace("|", r"\|").replace("\r\n", "\n").replace("\n", "<br>")


def _row(label: str, value: str | None = "") -> str:
    return f"| {label} | {_table_value(value)} |"


def render_record(values: dict[str, str]) -> str:
    value = lambda name: values.get(name, "")
    lines = [
        "# CI And Deployment Drill Record",
        "",
        "Generated by `scripts/ops/render_ci_deployment_drill_record.py`.",
        "Keep the filled copy in the release or operations log so every production readiness claim has evidence attached.",
        "",
        "## Summary",
        "",
        "| Field | Value |",
        "| --- | --- |",
        _row("Drill date (UTC)", value("drill_date_utc")),
        _row("Owner", value("owner")),
        _row("Repository", value("repository")),
        _row("Commit SHA", value("commit_sha")),
        _row("APP_VERSION", value("app_version")),
        _row("Environment", value("environment")),
        _row("Final decision"),
        "",
        "## GitHub Actions Evidence",
        "",
        "| Check | Evidence |",
        "| --- | --- |",
        _row("CI workflow run URL", value("ci_run_url")),
        _row("`db-integration` job result", value("db_integration_result")),
        _row("PostgreSQL smoke result"),
        _row("ClickHouse smoke result"),
        _row("Redis smoke result"),
        _row("Backend unit test result"),
        _row("Backend coverage gate result"),
        _row("Frontend lint/type/build result"),
        _row("Frontend smoke result"),
        _row("Uploaded artifacts"),
        "",
        "## Alert Webhook Drill Evidence",
        "",
        "| Check | Evidence |",
        "| --- | --- |",
        _row("Alert Webhook Drill run URL", value("alert_drill_run_url")),
        _row("`send` mode"),
        _row("Receiver"),
        _row("Firing notification received at"),
        _row("Resolved notification received at"),
        _row("Artifact `alert-webhook-drill-record`"),
        "",
        "## Deployment Smoke Evidence",
        "",
        "| Check | Command / Evidence |",
        "| --- | --- |",
        _row("Deployment smoke", value("deployment_smoke")),
        _row("Pull immutable images", "`docker compose -f docker-compose.prod.yml --env-file .env.production pull`"),
        _row("Start services", "`docker compose -f docker-compose.prod.yml --env-file .env.production up -d`"),
        _row("Service status", "`docker compose -f docker-compose.prod.yml --env-file .env.production ps`"),
        _row("Market readiness"),
        _row("Analysis metrics"),
        _row("Prometheus readiness"),
        _row("Grafana dashboards loaded"),
        _row("Alertmanager config loaded"),
        "",
        "## Rollback Check",
        "",
        "| Check | Evidence |",
        "| --- | --- |",
        _row("Rollback check", value("rollback_check")),
        _row("Previous known-good APP_VERSION"),
        _row("Rollback command rehearsed"),
        _row("Database migration rollback needed"),
        _row("Rollback owner confirmed"),
        "",
        "## Result",
        "",
        "| Field | Value |",
        "| --- | --- |",
        _row("Production-ready conclusion"),
        _row("Blocking issues", value("blocking_issues")),
        _row("Follow-up owner", value("follow_up_owner")),
        _row("Follow-up due date", value("follow_up_due_date")),
        "",
    ]
    return "\n".join(lines)


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render a CI and deployment drill record from CLI arguments or environment variables."
    )
    for field in FIELDS:
        parser.add_argument(
            f"--{field.name.replace('_', '-')}",
            default=None,
            help=f"{field.label}. Defaults to {field.env_var}, then GitHub Actions context when available.",
        )
    parser.add_argument("--output", help="Write the rendered Markdown to this path. Defaults to stdout.")
    return parser.parse_args(argv)


def values_from_args(args: argparse.Namespace) -> dict[str, str]:
    values: dict[str, str] = {}
    for field in FIELDS:
        cli_value = getattr(args, field.name)
        values[field.name] = cli_value if cli_value is not None else _field_default(field)
    return values


def write_output(markdown: str, output_path: str | None) -> None:
    if not output_path or output_path == "-":
        print(markdown, end="")
        return

    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(markdown, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    write_output(render_record(values_from_args(args)), args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
