from __future__ import annotations

import contextlib
import importlib.util
import io
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch


class AlertWebhookDrillRecordPrefillTests(unittest.TestCase):
    ROOT = Path(__file__).resolve().parents[2]
    SCRIPT = ROOT / "scripts/ops/alert_webhook_drill.py"

    @classmethod
    def setUpClass(cls) -> None:
        spec = importlib.util.spec_from_file_location("alert_webhook_drill", cls.SCRIPT)
        if spec is None or spec.loader is None:
            raise RuntimeError(f"Cannot load {cls.SCRIPT}")
        module = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = module
        spec.loader.exec_module(module)
        cls.module = module

    def test_dry_run_with_record_output_prefills_context_and_keeps_manual_fields_blank(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir, patch.dict(
            sys.modules[self.module.__name__].os.environ,
            {
                "DRILL_OWNER": "release-ops",
                "GITHUB_SERVER_URL": "https://github.com",
                "GITHUB_REPOSITORY": "acme/demo4",
                "GITHUB_RUN_ID": "4242",
                "ALERT_WEBHOOK_RECEIVER": "Feishu release channel",
            },
            clear=False,
        ):
            record_path = Path(tmpdir) / "alert-webhook-drill-record.md"
            result = subprocess.run(
                [
                    sys.executable,
                    str(self.SCRIPT),
                    "--url",
                    "https://alerts.example.invalid/manual-drill-token",
                    "--dry-run",
                    "--status",
                    "both",
                    "--record-output",
                    str(record_path),
                ],
                cwd=self.ROOT,
                text=True,
                capture_output=True,
                check=False,
            )

            self.assertEqual(0, result.returncode, result.stderr)
            self.assertTrue(record_path.exists(), "record output file was not created")
            markdown = record_path.read_text(encoding="utf-8")

        self.assertIn("| 负责人 | release-ops |", markdown)
        self.assertIn("| 接收端 | Feishu release channel |", markdown)
        self.assertIn(
            "| GitHub Actions run URL | https://github.com/acme/demo4/actions/runs/4242 |",
            markdown,
        )
        self.assertIn("| `send` mode | false (dry-run) |", markdown)
        self.assertIn("| `status` input | both |", markdown)
        self.assertIn("| HTTP firing response | not sent (dry-run) |", markdown)
        self.assertIn("| HTTP resolved response | not sent (dry-run) |", markdown)
        self.assertIn("Artifact `alert-webhook-drill-record`", markdown)
        self.assertIn("alert-webhook-drill-record artifact generated by this workflow run", markdown)
        self.assertIn("| 收到时间 | 待填写 |", markdown)
        self.assertIn("| 恢复告警 | 待填写 |", markdown)
        self.assertIn("| 结论 | 待填写 |", markdown)
        self.assertNotIn("manual-drill-token", markdown)
        self.assertNotIn("alerts.example.invalid", markdown)

    def test_send_with_record_output_prefills_http_results_without_leaking_secret_token(self) -> None:
        def fake_post_json(url: str, payload: dict[str, object], timeout: float) -> tuple[int, str]:
            status = payload["status"]
            if status == "firing":
                return 200, "firing accepted"
            return 202, "resolved accepted"

        with tempfile.TemporaryDirectory() as tmpdir, patch.dict(
            sys.modules[self.module.__name__].os.environ,
            {
                "DRILL_OWNER": "release-ops",
                "GITHUB_SERVER_URL": "https://github.com",
                "GITHUB_REPOSITORY": "acme/demo4",
                "GITHUB_RUN_ID": "9001",
            },
            clear=False,
        ), patch.object(self.module, "post_json", side_effect=fake_post_json), patch.object(
            self.module, "_utc_now", return_value="2026-05-07T08:30:00Z"
        ):
            record_path = Path(tmpdir) / "alert-webhook-drill-record.md"
            stdout = io.StringIO()
            with contextlib.redirect_stdout(stdout):
                exit_code = self.module.main(
                    [
                        "--url",
                        "https://hooks.slack.com/services/T000/B000/secret-token",
                        "--send",
                        "--status",
                        "both",
                        "--record-output",
                        str(record_path),
                        "--sleep-between",
                        "0",
                    ]
                )
            markdown = record_path.read_text(encoding="utf-8")

        self.assertEqual(0, exit_code)
        self.assertIn("POST firing payload to https://hooks.slack.com/<redacted> -> HTTP 200", stdout.getvalue())
        self.assertNotIn("secret-token", stdout.getvalue())
        self.assertIn("| 时间 | 2026-05-07T08:30:00Z |", markdown)
        self.assertIn("| `send` mode | true |", markdown)
        self.assertIn("| `status` input | both |", markdown)
        self.assertIn("| HTTP firing response | HTTP 200 |", markdown)
        self.assertIn("| HTTP resolved response | HTTP 202 |", markdown)
        self.assertIn("| 触发告警 | OpsWebhookDrill: firing payload sent (HTTP 200); resolved payload sent (HTTP 202) |", markdown)
        self.assertIn("| 负责人 | release-ops |", markdown)
        self.assertIn("| GitHub Actions run URL | https://github.com/acme/demo4/actions/runs/9001 |", markdown)
        self.assertIn("alert-webhook-drill-record artifact generated by this workflow run", markdown)
        self.assertNotIn("secret-token", markdown)
        self.assertNotIn("hooks.slack.com/services", markdown)

    def test_workflow_runs_single_script_path_that_writes_record_output(self) -> None:
        workflow = (self.ROOT / ".github/workflows/alert-webhook-drill.yml").read_text(encoding="utf-8")

        self.assertNotIn("--record-template --record-output", workflow)
        self.assertNotIn("Generate drill record template", workflow)
        self.assertIn("--record-output artifacts/alert-webhook-drill-record.md", workflow)
        self.assertIn("if [ \"${{ inputs.send }}\" = \"true\" ]; then", workflow)
        self.assertIn("python scripts/ops/alert_webhook_drill.py --send \\", workflow)
        self.assertIn("--dry-run \\", workflow)
        self.assertIn("upload-artifact@v4", workflow)
        self.assertIn("if-no-files-found: error", workflow)


if __name__ == "__main__":
    unittest.main()
